server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/binance?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: root
#    password: root
    url: jdbc:mysql://8.147.105.44:3306/ry_ba2?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Wj6xQGyH
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  # 邮件配置（使用 QQ邮箱 SMTP 示例）
  mail:
    host: smtp.qq.com
    port: 587
    username: 516720835@qq.com     # 替换为实际QQ邮箱
    password: utqcylcbcacpbihe     # QQ邮箱授权码(非QQ密码!)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# Binance API 配置
binance:
  base-url: https://demo-api.binance.com
  api-key: 9B8lqewcHNwP8DvkhMkRTcLEAP3Kk5qsk1AwEQrgeO0S4VNYHX70ftJEFZ3BgfhK
  secret-key: ZeEno8N9JYdc1waaxQ41D0qWPyU0YBTWRnggaZsrzALrqzwlMcTQw2DUvjlm6s0x
  # HTTP 代理（国内环境访问 Binance 时需要）
  proxy:
    enabled: true
    host: 127.0.0.1
    port: 7890
  # 邮件通知配置
  notification:
    email: 568237200@qq.com  # 接收通知的邮箱
